# Generated by Django 2.2.2 on 2019-07-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='template',
        ),
        migrations.AddField(
            model_name='category',
            name='template',
            field=models.CharField(default='blog/post_list.html', max_length=500, verbose_name='Шаблон'),
        ),
    ]
