# Generated by Django 2.2.2 on 2019-07-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190715_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='template',
            field=models.CharField(default='blog/post-list.html', max_length=500, verbose_name='Шаблон'),
        ),
    ]
