# Generated by Django 2.2.2 on 2019-07-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190717_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='message',
        ),
    ]
