# Generated by Django 2.2.2 on 2019-06-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190620_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Post'),
        ),
    ]
