# Generated by Django 2.2.2 on 2019-07-10 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='status',
        ),
        migrations.AddField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Отображение'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='Только для залогиненых'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='anchor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Якорь'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='Только для залогиненых'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'post'), ('model', 'post')), models.Q(('app_label', 'post'), ('model', 'category')), models.Q(('app_label', 'feedback'), ('model', 'feedbackmodel')), models.Q(('app_label', 'pages'), ('model', 'pages')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Ссылка на: '),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='object_id',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='ID записи'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Отображение'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название пункта на сайте'),
        ),
    ]
