# Generated by Django 2.2.2 on 2019-07-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190710_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'blog'), ('model', 'post')), models.Q(('app_label', 'blog'), ('model', 'category')), models.Q(('app_label', 'feedback'), ('model', 'feedbackmodel')), models.Q(('app_label', 'pages'), ('model', 'pages')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Ссылка на: '),
        ),
    ]
